# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ccellado <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/21 14:22:00 by ccellado          #+#    #+#              #
#    Updated: 2018/11/21 14:37:04 by ccellado         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME= ft_display_file

SRCS= main.c

all: build
		
build:
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRCS)
clean:

fclean: clean
	rm -f $(NAME)
