# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ccellado <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/03 23:55:46 by ccellado          #+#    #+#              #
#    Updated: 2018/11/03 23:56:08 by ccellado         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = eval_expr
SRCS = eval_expr.c foos.c

all: build

build:
	gcc -Wall -Wextra -Werror $(SRCS) -o $(NAME)
